version: "3"

services:
  db:
    image: mysql:8.2
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=laravel
    ports:
      - 8002:3306
#    volumes:
#      - ./db_data:/etc/mysql/conf.d
  app:
    image: devmayara/webserver:1.0
    volumes:
      - ./:/var/www/html
    ports:
      - 8001:80
    links:
      - db
    depends_on:
      - db
    tty: true